name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java16
      - name: Install Native Image
        run: gu install native-image
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: ./mvnw --batch-mode verify
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
      - name: Upload native-image configuration files
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v2
        with:
          name: native-image-configuration
          path: target/classes/META-INF/native-image
  non_windows_distributions:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: linux
          - os: macos-10.15
            target: osx
    name: ${{ matrix.target }} distribution
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download native-image configuration files
        uses: actions/download-artifact@v2
        with:
          name: native-image-configuration
          path: target/classes/META-INF/native-image
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java16
      - name: Install Native Image
        run: gu install native-image
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: |
          ./mvnw --batch-mode --activate-profiles assemble -Drevision=${{ github.event.inputs.version }} verify
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: connect-offset-reset-${{ matrix.target }}-x86_64.zip
          path: target/connect-offset-reset-*.zip
  windows_distribution:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: windows-2019
    name: windows distribution
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download native-image configuration files
        uses: actions/download-artifact@v2
        with:
          name: native-image-configuration
          path: target/classes/META-INF/native-image
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java16
      - name: Install Native Image
        run: gu install native-image
        shell: cmd
      - name: Install Visual C++ build tools workload for Visual Studio 2017 Build Tools
        run: choco install visualstudio2017-workload-vctools
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./mvnw --batch-mode --activate-profiles assemble -Drevision=${{ github.event.inputs.version }} verify
        shell: cmd
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: connect-offset-reset-windows-x86_64.zip
          path: target/connect-offset-reset-*.zip
  release:
    needs:
      - non_windows_distributions
      - windows_distribution
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download linux distribution
        uses: actions/download-artifact@v2
        with:
          name: connect-offset-reset-linux-x86_64.zip
          path: target
      - name: Download osx distribution
        uses: actions/download-artifact@v2
        with:
          name: connect-offset-reset-osx-x86_64.zip
          path: target
      - name: Download windows distribution
        uses: actions/download-artifact@v2
        with:
          name: connect-offset-reset-windows-x86_64.zip
          path: target
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Release
        uses: jreleaser/release-action@1.3.0
        with:
          version: early-access 
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
