name: ci

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04,macos-10.15,windows-2019]
        gu: [gu, gu.cmd]
        exclude:
          - os: ubuntu-20.04
            gu: gu.cmd
          - os: macos-10.15
            gu: gu.cmd
          - os: windows-2019
            gu: gu
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java11
      - name: Install Native Image
        run: ${{gu-binary}} install native-image
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: mvn-${{hashFiles('pom.xml')}}
          restore-keys: |
            mvn-
      - name: Build
        run: ./mvnw -B verify
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
