name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/cache@v2
        with:
          path: ~/repository/m2
          key: maven-${{hashFiles('pom.xml')}}
          restore-keys: |
            maven-
      - uses: DeLaGuardo/setup-graalvm@3.1
        with: 
          graalvm-version: 21.0.0.java11
      - run: gu install native-image
      - run: ./mvnw package
