name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.0.0.java11
      - name: Install Native Image
        run: gu install native-image
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: mvn-${{hashFiles('pom.xml')}}
          restore-keys: |
            mvn-
      - name: Build and test
        run: ./mvnw -B verify
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
