name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.1.0.java16
      - name: Install Native Image
        run: gu install native-image
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: mvn-${{hashFiles('pom.xml')}}
          restore-keys: |
            mvn-
      - name: Build
        run: ./mvnw --no-transfer-progress verify
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ${{os.matrix}}
    strategy:
      matrix:
        os: [ubuntu-20.04,macos-11.0,windows-2019]
    steps:
      -



