name: scan

on: push

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Run static analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-ci
